"use client";
import { usePathname } from "next/navigation";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, content }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        {children}
        {pathname == "/" && content}
      </body>
    </html>
  );
}
