"use client";
import { usePathname } from "next/navigation";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className="bg-slate-900 text-white">
        <header className="text-3xl font-semibold w-full text-center my-5 flex flex-col gap-5">
          <span className="bg-gradient-to-br  from-green-400 to-emerald-600 text-transparent bg-clip-text">
            WATCHING ANIMEK
          </span>
          <hr />
        </header>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
